sudo: required
services:
  - docker

before_install: 
  - docker build -t krizjiri3/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true krizjiri3/docker-frontend npm run test -- --coverage
  
language: generic 